version: '3.8'

services:
  frontend:
    image: ghcr.io/alejandroiga/frontendarroyoseco:latest
    container_name: arroyoseco-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - VITE_API_URL=https://backendarroyoseco.onrender.com/api